concatenate 的用法
---
串接陣列

In [0]:
import random
import numpy as np

q_f1 = np.ones((2,3,4))
p_f1 = np.zeros([3,3,4])

# 在第零維串接
a = np.concatenate([q_f1, p_f1], 0)

print(a)
print(a.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(5, 3, 4)


tf.range 用法
---
指定一個值,回傳由[0, 該值)的list

In [0]:
import tensorflow as tf
with tf.Session() as sess:
  # 指定一個值,回傳由[0, 該值)的list
  _27list = sess.run(tf.range(27))
  print(_27list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


tf.tile 用法
---
```
tile(
    input,     #输入
    multiples,  #维度上复制的次数, 幾個維度,list就有幾個元素,每個元素代表複製的倍數
    name=None
)
```

In [0]:
import tensorflow as tf
with tf.Session() as sess:
    _2dArray = sess.run(tf.reshape(tf.constant([1,2,3,4]), [2,2]))
    print("_2dArray = \n{}".format(_2dArray))

    #下面這行將row的部分重複3次, column重複兩次
    _new_tile_array = sess.run(tf.tile(_2dArray, [3, 2]))
    print("_new_tile_array = \n{}".format(_new_tile_array))

_2dArray = 
[[1 2]
 [3 4]]
_new_tile_array = 
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


np.argsort 用法
---
回傳array中排序後,元素在原本位置的index

In [0]:
import random
import numpy as np

# [(index, val)] = [(idx:0, val:3), (idx:1, val:1), (idx:2, val:2)]
# 依照Val排序後為[(idx:1, val:1), (idx:2, val:2), (idx:0, val:3), ]
a1 = np.array([3,1,2])
print(np.argsort(a1))

a = np.array(
    [[3,1,2,-1],
     [7,8,9,100],
     [10,9,8,-50]])
print(a)

indices = np.argsort(a, axis=1)
print('indices = {0}'.format(indices))
print('indices[:,0] = {0}'.format(indices[:,1]))

[1 2 0]
[[  3   1   2  -1]
 [  7   8   9 100]
 [ 10   9   8 -50]]
indices = [[3 1 2 0]
 [0 1 2 3]
 [3 2 1 0]]
indices[:,0] = [1 1 2]


# Tensor slicing用法

In [0]:
import random
import numpy as np

# 給一個shape為(60, 4, 4) 值為1的array
na = np.ones((60, 4, 4))
print(na.shape)
print('na.shape=' + str(na.shape))

# slicing 1
sc1 = na[10:20]  # 等同於sc1 = na[10:20, :, :], 省略後面兩個axis
print('sc1.shape=' + str(sc1.shape))

# slicing 2
sc2 = na[10:20, 0:2, 0:1]  # 每個axis可以獨立取slicing
print('sc2.shape=' + str(sc2.shape))

# slicing 3
sc3 = na[10:20, 1:-1, 1:-1]  # 可以給負數, [1:-1]]代表從第1個index到最後一個(但不包含,此例為3)index
print('sc3.shape=' + str(sc3.shape))


(60, 4, 4)
na.shape=(60, 4, 4)
sc1.shape=(10, 4, 4)
sc2.shape=(10, 2, 1)
sc3.shape=(10, 2, 2)


# Numpy array 可一次指定複數個索引

In [6]:
import numpy as np

batch_size = 4
features_dim = 6

train_data = np.zeros((batch_size, features_dim))
print(train_data)

# 直接指定第1 row裡的1, 2, 3 為 -1
train_data[1, [1, 2, 3]] = -1
print(train_data)

# 亦可用list直接指定
lsCol = [1, 2, 3]
train_data[1, lsCol] = 1
print(train_data)

# row 也可以直接複數指定
lsRow = [1, 2, 3]
train_data[lsRow, 0] = 2
print(train_data)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0. -1. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [2. 1. 1. 1. 0. 0.]
 [2. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0.]]
